name: Test wiki redirects

on:
  push:
    paths:
      - ".github/workflows/wiki-redirects.yml"
      - "salt/moin/**"
      - "tests/wiki-redirects/**"
  pull_request:
    paths:
      - ".github/workflows/wiki-redirects.yml"
      - "salt/moin/**"
      - "tests/wiki-redirects/**"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"

jobs:
  wiki-redirects:
    name: Hurl
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download Hurl ${{ env.HURL_VERSION }}
      run: >
        curl --no-progress-meter --location --fail
        --proto '=https' --tlsv1.2
        --output '/tmp/hurl.deb'
        "https://github.com/Orange-OpenSource/hurl/releases/download/${{ env.HURL_VERSION }}/hurl_${{ env.HURL_VERSION }}_amd64.deb"
      env:
        HURL_VERSION: "5.0.1"

    - name: Install Hurl
      run: sudo apt install --yes /tmp/hurl.deb

    - name: Run tests
      run: bash tests/wiki-redirects/test.sh
